<?php
// $Id$
/**
 * @author Bruno Massa http://drupal.org/user/67164
 * @file
 * Use Open Flash Chart on your site.
 *
 * @note only hooks are here.
 */

/**
 * Immplementation of hook_charts_info().
 *
 * Its a Charts module hook. It defines almost all aspects
 * of a chart provider, like its name, what types of charts
 * it can perform and what are the restrictions.
 */
function openflashchart_charts_info($op) {
  switch ($op) {
    case 'list':
      return array('openflashchart' => 'Open Flash Chart');

    case 'charttypes':
      return array(
        'line2D'  => t('Line 2D'),
        'vbar2D'  => t('Vertical Bar 2D'),
        'vbar3D'  => t('Vertical Bar 3D'),
        'pie2D'   => t('Pie 2D'),
      );
  }
}

/**
 * Immplementation of hook_charts_render().
 *
 * Its a Charts module hook. It transform the data into a HTML chart.
 *
 * @param &$data
 *   Array. The
 */
function openflashchart_charts_render(&$data) {
  // Include the specific Open Flash Chart helper functions
  include_once drupal_get_path('module', 'openflashchart') .'/openflashchart.inc';

  $chart = new open_flash_chart_api();

  if ($error = _openflashchart_chart($chart, $data)) {
    return $error;
  }

  if ($error = _openflashchart_series($chart, $data)) {
    return $error;
  }

  return $chart->render();
}
