<?php
// $Id$
/**
 * @author Bruno Massa http://drupal.org/user/67164
 * @file fusioncharts.module
 * Use FusionCharts on your site.
 *
 * @note only hooks are here.
 */

/**
 * Immplementation of hook_chartsapi().
 *
 * Its a Charts module hook. It defines almost all aspects
 * of a chart provider, like its name, what types of charts
 * it can perform and what are the restrictions.
 */
function fusioncharts_chartsinfo($op) {
  switch ($op) {
    case 'list':
      return array('fusioncharts' => 'FusionCharts');

    case 'charttypes':
      return array(
        'line2D'  => t('Line 2D'),
        'hbar2D'  => t('Horizontal Bar 2D'),
        'vbar2D'  => t('Vertical Bar 2D'),
        'pie2D'   => t('Pie 2D'),
      );
  }
}

/**
 * Immplementation of hook_chartsapi().
 *
 * Its a Charts module hook. It transform the data into a HTML chart.
 *
 * @param &$data
 *   Array. The
 */
function fusioncharts_chartsapi(&$data) {
  // Include the specific Google Chart API helper functions
  include_once drupal_get_path('module', 'fusioncharts') .'/fusioncharts.inc';

  // Convert the chat TYPE into the FusionCharts way.
  // Since its a requirement to build the chart on Google, if the value
  // was not found, return nothing and stop the execution.
  $options = array(
    'line2D'  => '/swf/MSLine.swf',
  );
  if (empty($options[$data['#type']])) {
    return t('This type is not possible using %chartplugin',
      array('%chartplugin' => 'FusionCharts'));
  }
  $file = url(drupal_get_path('module', 'fusioncharts') . $options[$data['#type']]);

  // Convert the chat SIZE into the FusionCharts way.
  // Since its a requirement to build the chart on Google, if the value
  // was not found, return nothing and stop the execution.
  if (empty($data['#width']) or empty($data['#height'])) {
    return '';
  }
  $width  = $data['#width'];
  $height = $data['#height'];

  $chart = array();

  if ($message = _fusioncharts_chart($chart, $data)) {
    return $message;
  }

  if ($message = _fusioncharts_series($chart, $data)) {
    return $message;
  }

  $chart =  '&dataXML='. str_replace('"', "'", format_xml_elements($chart));

  // Its the HTML tag to include the chart
  return <<<FUSIONCHARTS
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000">
  <param name="allowScriptAccess" value="always" />
  <param name="FlashVars" value="$chart" />
  <param name="quality" value="high" />
  <embed src="$file" flashVars="$chart" width="$width" height="$height" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>
FUSIONCHARTS;
}
